openapi: "3.0.3"
info:
  version: 1.0.0
  title: API for Disashop Challenge HackUDC 2024
  description: This API provides support for the Disashop challenge of HackUDC 2024. The API allows fetching a generic form definition, as well as the subsequent creation of data based on those forms, and retrieval of that data.
tags:
  - name: Form Types
    description: Endpoints related to form types
  - name: Forms
    description: Endpoints related to forms
servers:
  - url: https://48fcef17-883f-49d8-8d0f-6a9a559d107b.mock.pstmn.io
    description: Mock Server   
paths:
  /api/v1/formTypes:
    get:
      operationId: getFormTypes
      summary: Get available form types
      description: Returns a list of available form types.
      tags:
        - Form Types
      responses:
        '200':
          description: List of form types
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - form_type_id
                    - form_type_name
                  properties:
                    form_type_id:
                      description: 'Unique identifier of a form type.'
                      type: integer
                      format: int32
                      example: 1
                    form_type_name:
                      description: 'Name of the form type.'
                      type: string
                      example: Raspberry Registration
                    form_type_description:
                      description: 'Description of the form type.'
                      type: string
                      example: 'This form type is used to register information about Raspberry Pi devices.'
        '500':
          $ref: '../#/components/responses/500InternalServerError'
  /api/v1/formTypes/{form_type_id}:
    get:
      operationId: getFormTypeDetail
      summary: Get form type
      description: Returns a specific form type.
      tags:
        - Form Types
      parameters:
        - in: path
          name: form_type_id
          description: 'Unique identifier of a form type.'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: Form type
          content:
            application/json;charset=utf-8:
              schema:
                type: object
                required:
                  - form_type_id
                  - form_type_name
                  - title_field
                properties:
                  form_type_id:
                    description: 'Unique identifier of a form type.'
                    type: integer
                    format: int32
                    example: 1
                  form_type_name:
                    description: 'Name of the form type.'
                    type: string
                    example: Raspberry Registration
                  title_field:
                    description: 'Title field of the form type.'
                    type: object
                    required:
                      - field_description
                    properties:
                      field_description:
                        description: 'Description of the field.'
                        type: string
                        example: 'Description of the field'
                  form_groups:
                    description: 'List of form groups.'
                    type: array
                    items:
                      type: object
                      required:
                        - group_id
                        - group_name
                      properties:
                        group_id:
                          description: 'Unique identifier of a form group.'
                          type: string
                          example: 'basic_info'
                        group_name:
                          description: 'Name of the group.'
                          type: string
                          example: Basic information
                        group_description:
                          description: 'Description of the group.'
                          type: string
                          example: Basic information about the device you are registering
                        group_order:
                          description: 'Order of the group.'
                          type: integer
                          example: 1
                  form_fields:
                    description: 'List of fields of the form type.'
                    type: array
                    items:
                      type: object
                      required:
                        - field_id
                        - field_name
                        - field_type
                        - field_order
                        - field_description
                      properties:
                        field_id:
                          description: 'Unique identifier of a field.'
                          type: integer
                          format: int32
                          example: 1
                        field_name:
                          description: 'Name of the field.'
                          type: string
                          example: Serial Number
                        field_type:
                          description: 'Type of the field.'
                          type: string
                          example: text
                        field_order:
                          description: 'Order of the field.'
                          type: integer
                          example: 1
                        field_required:
                          description: 'Indicates if the field is required.'
                          type: boolean
                          example: true
                        field_description:
                          description: 'Description of the field.'
                          type: string
                          example: 'Description of the field'
                        field_readonly:
                          description: 'Indicates if the field is readonly.'
                          type: boolean
                          example: false
                        field_default_value:
                          description: 'Default value of the field.'
                          example: 'Default value (can be any basic type)'
                        field_group:
                          description: 'Id of the group this field belongs to, if any'
                          type: string
                          example: 'basic_info'
                        field_dependent_on:
                          type: object
                          description: 'Field that this field depends on. This filed should only be visible if the dependent field has the specified value.'
                          properties:
                            field_id:
                              description: 'Unique identifier of the field.'
                              type: integer
                              format: int32
                              example: 1
                            field_value:
                              description: 'Value of the field.'
                              example: '123123322132145'
                        field_validations:
                          description: 'List of validations of the field.'
                          type: object
                          properties:
                            min_length:
                              description: 'Minimum length of the field.'
                              type: integer
                              example: 1
                            max_length:
                              description: 'Maximum length of the field.'
                              type: integer
                              example: 100
                            format:
                              description: 'Format of the field.'
                              type: string
                              example: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
                            allow_multiple_options:
                              description: 'Indicates if the field allows multiple options.'
                              type: boolean
                              example: true  
                            options:
                              description: 'List of options of the field.'
                              type: array
                              items:
                                type: string
                                example: 'Option 1'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /api/v1/forms: 
    get:
      operationId: getForms
      summary: Get covered forms
      description: Returns a list of all created forms, optionally filtered by form type.
      tags:
        - Forms
      parameters:
        - in: query
          name: form_type_id
          description: 'Unique identifier of a form type.'
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: List of forms
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - form_id
                    - title_field
                    - form_type_id
                  properties:
                    form_id:
                      description: 'Unique identifier of a form.'
                      type: integer
                      format: int32
                      example: 1
                    title_field:
                      description: 'Title of the form.'
                      type: string
                      example: Raspberry Pi 5
                    form_type_id:
                      description: 'Unique identifier of a form type.'
                      type: integer
                      format: int32
                      example: 1
    post:
      summary: Create form
      description: Creates a new form.
      tags:
        - Forms
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              type: object
              required:
                - form_type_id
                - title_field
                - form_fields
              properties:
                form_type_id:
                  description: 'Unique identifier of a form type.'
                  type: integer
                  format: int32
                  example: 1
                title_field:
                  description: 'Title field of the form.'
                  type: string
                  example: 'Raspberry Pi 5'
                form_fields:
                  description: 'List of fields of the form.'
                  type: array
                  items:
                    type: object
                    required:
                      - field_value
                      - field_id
                    properties:
                      field_value:
                        description: 'Value of the field.'
                        type: string
                        example: '123123322132145'
                      field_id:
                        description: 'Unique identifier of a field.'
                        type: integer
                        format: int32
                        example: 1
      responses:
        '201':
          description: Form created successfully
        '400':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /api/v1/forms/{form_id}:
    get:
      operationId: getForm
      summary: Get form
      description: Returns a specific form.
      tags:
        - Forms
      parameters:
        - in: path
          name: form_id
          description: 'Unique identifier of a form.'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: Form
          content:
            application/json;charset=utf-8:
              schema:
                type: object
                required:
                  - form_id
                  - form_type_id
                  - title_field
                  - form_fields
                properties:
                  form_id:
                    description: 'Unique identifier of a form.'
                    type: integer
                    format: int32
                    example: 1
                  form_type_id:
                    description: 'Unique identifier of a form type.'
                    type: integer
                    format: int32
                    example: 1                    
                  title_field:
                    description: 'Title field of the form.'
                    type: string
                    example: 'Raspberry Pi 5'
                  form_fields:
                    description: 'List of fields of the form.'
                    type: array
                    items:
                      type: object
                      required:
                        - field_id
                        - field_value
                      properties:
                        field_id:
                          description: 'Unique identifier of a field.'
                          type: integer
                          format: int32
                          example: 1
                        field_value:
                          description: 'Value of the field.'
                          type: string
                          example: '123123322132145'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'  
components:
  responses:
    400BadRequest:
      description: 'Bad Request'
    404NotFound:
      description: 'Not Found'
    500InternalServerError:
      description: 'Internal Server Error'